[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "glycoprotein-particle-screening"
version = "0.1.0"
description = "Screen particle picks from a pytom/RELION-style STAR file by eye, oriented to each particle's own orientation."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer",
    "mrcfile",
    "starfile",
    "scipy",
    "numpy",
    "pandas",
    "typing_extensions",
    "flask",
    "matplotlib"
]

[project.scripts]
#creates a terminal command called 'gps' pointing to the 'app' variable in cli.py
gps = "gps.cli:app"

[tool.setuptools.packages.find]
where = ["src"]
